import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillRead,
  AiFillBook,
  AiOutlineDownload,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/jay.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import k8s from "../public/system_design.png";
import event_finder from "../public/event_finder.png";
import micrograd from "../public/micrograd.png";
import gat from "../public/graph_attention_networks.png";
import makemore from "../public/makemore.png";
import nn_attacks from "../public/699_adversarial_attacks.png";
import spiro from "../public/spiro.png";
import KNN from "../public/KNN.png";
import pente from "../public/pente.png";
import resolution from "../public/resolution.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [dropdownOpen, setDropdownOpen] = useState(false);
  const [activePDF, setActivePDF] = useState("");

  const handlePDFOpen = (pdfPath) => {
    setDropdownOpen(false);
    setActivePDF(pdfPath);
  };

  const handleClose = () => {
    setActivePDF(""); // Resets the activePDF state, hiding the iframe
  };

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portfolio Jay Joshi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portfolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li className="relative">
                <button
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  onClick={() => setDropdownOpen(!dropdownOpen)}
                >
                  Resume
                </button>
                {dropdownOpen && (
                  <ul className="absolute right-0 w-48 mt-2 py-2 bg-gradient-to-r from-cyan-500 to-teal-500 text-white shadow-xl rounded-lg">
                    <li
                      className="px-4 py-2 hover:bg-gradient-to-r from-cyan-400 to-teal-400 rounded-lg cursor-pointer"
                      onClick={() => handlePDFOpen("Resume_Jay_Joshi.pdf")}
                    >
                      ML Engineer
                    </li>

                    <li
                      className="px-4 py-2 hover:bg-gradient-to-r from-cyan-400 to-teal-400 rounded-lg cursor-pointer"
                      onClick={() => handlePDFOpen("Resume_swe_Jay.pdf")}
                    >
                      Software Engineer
                    </li>

                    <li
                      className="px-4 py-2 hover:bg-gradient-to-r from-cyan-400 to-teal-400 rounded-lg cursor-pointer"
                      onClick={() => handlePDFOpen("CV_Jay_Joshi.pdf")}
                    >
                      CV
                    </li>
                  </ul>
                )}
              </li>
            </ul>
          </nav>
          <div>
            {activePDF && (
              <div className="dark:shadow-gray-700 shadow-lg px-4 py-4 flex flex-col items-end relative">
                <iframe
                  src={activePDF}
                  className="w-full h-96 lg:h-[500px]"
                  title="Resume"
                ></iframe>
                <div className="flex justify-end space-x-3 mt-4">
                  <div className="flex items-center mt-4">
                    <p className="dark:text-red-600 text-red-600">
                      Note: Please download the resume to acess all links
                    </p>
                  </div>
                  <a
                    href={activePDF}
                    download
                    className="bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded flex items-center mt-4"
                  >
                    <div className="flex gap-2">
                      <p>Download</p>
                      <AiOutlineDownload />
                    </div>
                  </a>
                  <button
                    onClick={handleClose}
                    className="mt-4 bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded self-end "
                  >
                    Close
                  </button>
                </div>
              </div>
            )}
          </div>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Jay Joshi
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Machine Learning Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I'm a Machine Learning Engineer based in California. I have a
              passion for software development and love to learn new
              technologies. I have experience in building machine learning
              models and web applications. I am currently looking for full-time
              opportunities in the field of Machine Learning and Software
              Development.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/jyjoshi/" target="blank">
                <AiFillGithub />
              </a>
              <a href="https:linkedin.com/in/jyjoshi" target="blank">
                <AiFillLinkedin />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">
              Core competencies
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              {/* Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use. */}
              I am a software engineer and machine learning specialist with
              advanced degrees in Computer Science and Engineering from the
              University of Southern California and the University of Pune. I
              specialize in developing machine learning models and have led
              projects like the auto-regressive character level language model
              and a tiny autograd engine. Proficient in languages like Python,
              JavaScript, and Java, I also excel in technologies such as
              PyTorch, Docker, and Kubernetes.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              My technical expertise extends to designing efficient software
              solutions and systems, notably demonstrated in my "Food Ready"
              project, which significantly improved operational efficiencies and
              customer satisfaction. My commitment to community service and
              educational outreach is evident through my active volunteer work,
              underscoring my capabilities as a leader in both technical and
              community-focused roles.
            </p>
          </div>

          {/* Projects - 1 */}
          <div className="lg:flex gap-10">
            {/* Video to Mp3 Converter */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={k8s}
                width={100}
                height={50}
                layout="responsive"
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Video to Mp3 Converter
              </h3>
              <p className="py-2">
                A Kubernetes Microservice Orchestration Project that converts
                video files to mp3 files.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Python, Flask</p>
              <p className="text-gray-800 py-1">MongoDB, MySQL</p>
              <p className="text-gray-800 py-1">Docker, Kubernetes</p>
              <p className="text-gray-800 py-1">RabbitMQ</p>

              <div className="flex gap-4 lg:gap-10 justify-center">
                <a
                  href="https://github.com/jyjoshi/k8s_system_design"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
            {/* Event Finder */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={event_finder}
                width={1.67}
                height={1}
                layout="responsive"
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Event Finder</h3>
              <p className="py-2">
                A web application that allows users to search for live events.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Angular</p>
              <p className="text-gray-800 py-1">HTML,CSS</p>
              <p className="text-gray-800 py-1">TypeScript</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Google Cloud</p>
              <div className="flex gap-4 lg:gap-10 justify-center">
                <a
                  href="https://github.com/jyjoshi/EventFinder-angular"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
                <a
                  href="https://ticketmaster-angular.wl.r.appspot.com/"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    Website
                  </button>
                </a>
              </div>
            </div>
          </div>

          {/* Projects - 2 */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={micrograd}
                width={200}
                height={80}
                layout="responsive"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Micrograd</h3>
              <p className="py-2">
                A minimalistic neural network library designed to facilitate an
                understanding of the inner workings of neural networks.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Jupyter</p>
              <p className="lg:py-3"></p>
              <p className="lg:py-3"></p>
              <div className="flex gap-4 lg:gap-10 justify-center">
                <a href="https://github.com/jyjoshi/micrograd" target="_blank">
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={gat}
                width={200}
                height={80}
                layout="responsive"
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Heterogeneous Link Prediction in Graphs
              </h3>
              <p className="py-2">
                Implemented a link prediction model using Subgraph Sketching and
                Graph Attention Networks.
              </p>
              <p className="py-2">
                Achieved 6th place on the ogbl-biokg leaderboard with an MRR of
                0.8414 while using significantly less parameters as compared to
                the top models.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Pytorch Geometric</p>
              <p className="text-gray-800 py-1">Jupyter</p>
              <p className="text-gray-800 py-1">Latex</p>

              <div className="flex gap-4 lg:gap-10 justify-center">
                <a
                  href="https://drive.google.com/file/d/19lBOcHphzDgsp72b7P9uGqoBJRm7TOf3/view"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Paper</div>
                      <div>
                        <AiFillRead />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
          </div>
          {/* Projects - 3 */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={makemore}
                width={130}
                height={100}
                layout="responsive"
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Makemore</h3>
              <p className="py-2">
                An autoregressive character level language model that generates
                new names for people.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">PyTorch</p>
              <p className="text-gray-800 py-1">Matplotlib</p>
              <p className="text-gray-800 py-1">Jupyter</p>
              <p className="text-gray-800 py-1">Python</p>
              <div className="flex gap-4 lg:gap-10 justify-center">
                <a href="https://github.com/jyjoshi/makemore" target="_blank">
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image
                src={nn_attacks}
                width={200}
                height={100}
                layout="responsive"
                className="rounded-3xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Triggered Adversarial Attacks in Neural Networks
              </h3>
              <p className="py-2">
                Demonstrated the potential of triggered adversarial examples to
                remain hidden and affect specific neural networks only under
                certain conditions,
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Latex</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Jupyter</p>
              <p className="lg:py-3"></p>
              <p className="lg:py-3"></p>
              <div className="flex gap-4 lg:gap-10 justify-center">
                <a
                  href="https://drive.google.com/drive/folders/15Nxage_ktvx77t90gFPxFOR2D2GYBPfu"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Paper</div>
                      <div>
                        <AiFillRead />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
          </div>

          {/* Projects - 4 */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={spiro}
                width={300}
                height={200}
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Geospatial Data Visualization and Analysis
              </h3>
              <p className="py-2">
                Visualized and analysed geospatial data using various methods
                including spirographs, KNN (K-Nearest Neighbors), convex hull
                algorithms, and the use of SQL queries for data manipulation.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">MySQL</p>

              <div className="flex gap-4 lg:gap-10 justify-center">
                <a href="https://github.com/jyjoshi/geoviz" target="_blank">
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={resolution}
                width={200}
                height={200}
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Propositional Inference Engine
              </h3>
              <p className="py-2">
                A propositional logic-based knowledge base (KB) with unit
                resolution for automated logical inference, enabling the system
                to ascertain if a provided statement can be logically deduced
                from the stored facts.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Pytorch Geometric</p>
              <p className="text-gray-800 py-1">Jupyter</p>
              <p className="text-gray-800 py-1">Latex</p>

              <div className="flex gap-4 lg:gap-10 justify-center">
                <a
                  href="https://github.com/jyjoshi/PropInferenceEngine"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
          </div>

          {/* Projects - 5 */}
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image
                src={pente}
                width={200}
                height={200}
                className="rounded-xl"
              />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Pente Game Agent
              </h3>
              <p className="py-2">
                An agent designed to play pente using minimax algorithm and
                alpha-beta pruning.
              </p>
              <p className="py-2">
                Achieved 6th place on the ogbl-biokg leaderboard with an MRR of
                0.8414 while using significantly less parameters as compared to
                the top models.
              </p>
              <h4 className="py-2 text-teal-600">Tech Used</h4>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Pytorch Geometric</p>
              <p className="text-gray-800 py-1">Jupyter</p>
              <p className="text-gray-800 py-1">Latex</p>

              <div className="flex gap-4 lg:gap-10 justify-center">
                <a
                  href="https://github.com/jyjoshi/pente_game_agent"
                  target="_blank"
                >
                  <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md mt-4">
                    <div className="flex justify-center gap-1 items-center">
                      <div>Code</div>
                      <div>
                        <AiFillGithub />
                      </div>
                    </div>
                  </button>
                </a>
              </div>
            </div>
            <div className="flex-1"></div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance designer and
              developer, I've done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
